### ISSUE TITLE
InfluxDB Java client doesn't work for 1.0.0~rc1 version

### ISSUE THREAD

**Issue by fandw06** [influxdata/influxdb-java#191]
I use InfluxDB java client in my project. It works fine for 0.13.1 version, however, it doesn't work for 1.0.0~rc1. When I created a database using sample code:

        InfluxDB influxDB = InfluxDBFactory.connect("http://localhost:8086", "root", "root");
        String dbName = "aTimeSeries";
        influxDB.createDatabase(dbName);

It works for 0.13.1, but there is an error for 1.0.0~rc:

Exception in thread "main" java.lang.RuntimeException: {"error":"error parsing query: found NOT, expected ; at line 1, char 20"}

**Comment by rossmcdonald** [comment]
It looks like it's caused by the use of the `IF NOT EXISTS` phrase, which was removed with https://github.com/influxdata/influxdb/pull/7077.

[This](https://github.com/influxdata/influxdb-java/blob/13098d09f1e97ec8f9cda73fb9bcf8d05603e8a9/src/main/java/org/influxdb/impl/InfluxDBImpl.java#L205) line should probably be updated accordingly.

**Comment by bansap004** [comment]
I see the same issue with InfluxDB shell version: v1.0.0, any path of upgrade which fixes this issue ?
