### ISSUE TITLE
Support dynamic measurement name in InfluxDBResultMapper

### ISSUE THREAD

**Issue by dparmar** [influxdata/influxdb-java#371]
In my case the measurement name is not known at compile time. So I was wondering if toPOJO() can take it as a parameter.

As a quick fix, currently I extend InfluxDBResultMapper and override getMeasurementName, but that doesn't look like elegant solution.

Thanks for this very useful feature.

**Comment by fmachado** [comment]
@dparmar we could add a new parameter to `toPOJO` method where you could pass a measurement name. But before we do it, I'm curious: how do you name your measurements? Are you naming them using a pattern like `<measurement>_yyyymmdd` (e.g. `cpu_20170901`)?

**Comment by dparmar** [comment]
They are user defined names like test_1, test_2

**Comment by martinschuberts** [comment]
Why don't you use then a database or tag for it?
We for example have a database for each user - so we can clearly separate the data and access to it.
But the measurements are the same - just the tag values are different. 
I am curious about your use-case and approach.

**Comment by ikercrg** [comment]
We have also the same problem. The solution suggested about adding a new parameter to `toPojo` would be great. 

We do not follow any specific pattern to name the measurements; sometimes it is name_subname or name.subname, etc..

Do you need more info, because this feature would be very interesting for us.

Thanks in advance
