### ISSUE TITLE
Question: Any support for Reactive streams / RxJava integration or non-blocking alternative?

### ISSUE THREAD

**Issue by dfernandezm** [influxdata/influxdb-java#392]
Hi all,

Sorry if this is a dumb question, I am a beginner in InfluxDB and this library. I would like to invoke it for a high volume of input coming from a Java application. That application will use RxJava / Reactive Streams all the way, so it is completely non-blocking.
Is it supported at all? Any pointers to a possible wrapping of the current calls so that they are observables or equivalent?

**Comment by fmachado** [comment]
@dfernandezm IMO there is a feasible approach for reactive streams with the current API. However it's important to notice that it may not be the best solution and the API will probably be rewritten soon (for a more complete overview about existing issues, check [this document](https://github.com/influxdata/influxdb-java/wiki/Client-Improvements-Plan)).

I'm assuming that you want to write as may points in one HTTP call as possible. So I would:
1) Enable the batch mode (`org.influxdb.impl.InfluxDBImpl.enableBatch(int, int, TimeUnit, ThreadFactory, BiConsumer<Iterable<Point>, Throwable>)`);
2) Create a `BiConsumer` to notify my Observable for errors. Currently we don't have  a way to notify on successful writes (this issue is mentioned on the document).

BTW, any contribution here (e.g. a refactoring to support `CompletableFuture` or another approach that do not add external dependencies) would be great! :)
