### ISSUE TITLE
flush duration interval jittering

### ISSUE THREAD

**Issue by dubsky** [influxdata/influxdb-java#397]
InfluxDB clients are likely to be deployed on many hosts. Also, it may happen that these hosts are all started at once. When this happens and all of them have values to write (it is even worse when they have to write data that were buffered while the clients were down) it easily happens that InfluxDB server gets overloaded because the instance wasn't scaled for such spike in load.

As a solution used in Influx Telegraf and perhaps other clients is to introduce variability in the interval between flushes of buffered data point writes.

Obsoletes #395

**Comment by fmachado** [comment]
If I'm not wrong, on a [clustered environment it's possible to have the same client configured with multiple URIs (nodes)](https://docs.influxdata.com/enterprise_influxdb/v1.3/guides/https_setup/#connect-telegraf-to-a-secured-influxenterprise-instance).

Based on this assumption (a client configured with multiple nodes), should we consider trying another host instead of the busy one?

**Comment by dubsky** [comment]
@fmachado I think this is a good place for discussion. Anyway, while working on this one I realized I will have to do also #396. I have committed a proposal already, please take a look so that I know I am going in the right direction with the API.

**Comment by fmachado** [comment]
@dubsky yeah, I have the feeling that I am hijacking your issue to deal with something that (maybe) is not totally related ("failover to another node" while your issue is related with "interval jittering" during the flush).
