### ISSUE TITLE
How to create a new database or connect to an existing one if it already exists

### ISSUE THREAD

**Issue by bitbythecron** [influxdata/influxdb-java#456]
Looks like `InfluxDb#createDatabase(...)` is deprecated as of 2.10, but all the code samples on the README demonstrate it being used.

I'm looking for what I need to do to connect to my InfluxDB instance and either:

1. Create a new DB (named, say "*myappdb*") if its doesn't exist; or
2. Connect to the existing *myappdb* if it does already exist

```
InfluxDB influxDB = InfluxDBFactory.connect("http://localhost:8086", "root", "root");
// TODO: How to check if a "myappdb" database exists already or not?!
```

Any ideas?

**Comment by wuyongfa123** [comment]
nobody knows？

**Comment by lxhoan** [comment]
to check if a DB has existed or not, you can use Schema exploration using InfluxQL:
https://docs.influxdata.com/influxdb/v1.5/query_language/schema_exploration/
or use the helper method InfluxDB.databaseExists(String)

Beware that this method as well as other helper methods (such as createDatabase(...)) are marked as deprecated and gonna dropped in future release due to we want to keep the client API as thin and as much consistent to the server API as possible. So please consider to use directly the corresponding InfluxQL statement for your purpose

**Comment by lxhoan** [comment]
closed due to no disapproval
