### ISSUE TITLE
Float precision changes

### ISSUE THREAD

**Issue by qiaojialin** [influxdata/influxdb-java#469]
I found that the precision in influxdb of a field using float in java will change but double not.

![image](https://user-images.githubusercontent.com/7240743/42919828-5d0a155e-8b46-11e8-8728-27e87d14826a.png)

I think this should be fixed.

**Comment by lxhoan** [comment]
single-precision 32-bit IEEE 754 floating point data type (java: float) will be converted to double-precision 64-bit IEEE 754 floating point (java: double) since InfluxDB server recognizes double-precision value only

(check https://docs.influxdata.com/influxdb/v1.6/write_protocols/line_protocol_reference/#data-types)

Conversion from float to double is not as straightforward as conversion integer since no 'real' floating point data in memory, it's impossible to model continuous values in a digital computer (that's why we have the 'precision' here). There are a lot discussion on this topic, you can find one easily.

In general I strongly suggest you to use double because that is the official data type of influxdb server
