### ISSUE TITLE
FR: depedency to okhttp has to many limitations

### ISSUE THREAD

**Issue by mburger81** [influxdata/influxdb-java#536]
Hallo, we try to use your very good java library to be used on an embedded IoT System.

Anything looks good expecting to have to load okHttp as external dependency this has two many other dependencies which we can not use on embedded systems.

So my question is, would it not possible to abstract the http calls where we can use different implementations using okhttp or in our case change it with apache httpclient and other implementations?

This would really useful if others like us could or would not use okhttp because they use already other http clients?

**Comment by majst01** [comment]
Hi,
changing the http-client implementation, or make it configurable will be a non trivial task.
Okhttp does not have many external dependencies, what are your concerns ?
Size of the jar, memory consumption, cpu usage, can you please elaborate.

**Comment by fmachado** [comment]
@mburger81 in my opinion, this library is **not** suitable for embedded devices simply because pushing data from the producer/gateway directly to the timeseries database is not the correct approach, unless you don't care about security or performance or data integrity is not important at all.

> but we have created many libs for high performance, like a faster json parser which is running native on system.
Pushing data to InfluxDB is just about sending HTTP requests or UDP packets. If you are rewriting libraries that are being maintained by the community for years because you understand that what you are creating is better, then I think influxdb-java will be another candidate.

There is another library for writing[1] data into InfluxDB that may be useful for you but I don't know if it's still maintained. 

By the way, I'm highly interested on any (published) academic paper or successful commercial product that you may know and that are using the architecture you are developing.

[1] https://github.com/brettwooldridge/influx4j

**Comment by bednar** [comment]
@mburger81 the upcoming version of [influxdb-client-java](https://github.com/influxdata/influxdb-client-java/) has a bundle for OSGi environment - https://github.com/influxdata/influxdb-client-java/tree/master/client-osgi. There will be also supports for Apache Karaf.
