### ISSUE TITLE
How can I find the sum of the point?

### ISSUE THREAD

**Issue by jianghongtao0228** [influxdata/influxdb-java#589]
I am learning to use Influxdb。
I have a measurement such as:
```
-----------------------------------------------------
name: test
time  tag_a   field_a 
----   -----   -------
xxx    1         a
xxx    (null)    b  
xxx    2       (null)
------------------------------------------------------
```
when I execute `"select count(tag_a) from test"` 
the return value is 2(not include null value)
How can I find the total count of this measurement include null value？
（like `“select count(*) from xxx”` in mysql）

**Comment by fmachado** [comment]
Hi @jianghongtao0228 ,

This is not the best place to ask this kind of question because this issue tracker here is dedicated to the influxdb-java project. Feel free to ask but it may take some time until you have an answer so I highly recommend you to ask your question on StackOverflow or on [InfluxDB Community Forum](https://community.influxdata.com/).

As explained on the [InfluxDB documentation about the function COUNT](https://docs.influxdata.com/influxdb/v1.7/query_language/functions/#count):

> COUNT()
> Returns the number of non-null field values.
